export const FETCH_ALL_BLOG = 'FETCH_ALL_BLOG';
export const FETCH_ALL_BLOG_SUCCESS = 'FETCH_ALL_BLOG_SUCCESS';
export const FETCH_ALL_BLOG_FAIL = 'FETCH_ALL_BLOG_FAIL';

export const UPDATE_BLOG = 'UPDATE_BLOG';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';

export const ADD_BLOG =  'ADD_BLOG';
export const ADD_BLOG_SUCCESS =  'ADD_BLOG_SUCCESS';
export const ADD_BLOG_FAIL =  'ADD_BLOG_FAIL';

export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';



export const ACTIVE_BLOG = 'ACTIVE_BLOG';
export const ACTIVE_BLOG_SUCCESS = 'ACTIVE_BLOG_SUCCESS';
export const ACTIVE_BLOG_FAIL = 'ACTIVE_BLOG_FAIL';

export const RESET_STORE = 'RESET_STORE';