export const FETCH_USER_WALLETS= 'FETCH_USER_WALLETS';
export const FETCH_USER_WALLETS_SUCCESS = 'FETCH_USER_WALLETS_SUCCESS';
export const FETCH_USER_WALLETS_FAIL = 'FETCH_USER_WALLETS_FAIL';

export const CLOSE_USER_WALLET = 'CLOSE_USER_WALLET';
export const CLOSE_USER_WALLET_SUCCESS = 'CLOSE_USER_WALLET_SUCCESS';
export const CLOSE_USER_WALLET_FAIL = 'CLOSE_USER_WALLET_FAIL';

export const RESET_STORE = 'RESET_STORE';