export const FETCH_USER_WALLETS= 'FETCH_USER_WALLETS';
export const FETCH_USER_WALLETS_SUCCESS = 'FETCH_USER_WALLETS_SUCCESS';
export const FETCH_USER_WALLETS_FAIL = 'FETCH_USER_WALLETS_FAIL';

export const FETCH_USER_WALLET = 'FETCH_USER_WALLET';
export const FETCH_USER_WALLET_SUCCESS = 'FETCH_USER_WALLET_SUCCESS';
export const FETCH_USER_WALLET_FAIL = 'FETCH_USER_WALLET_FAIL';

export const FETCH_RECIPIENTS_LOCAL = 'FETCH_RECIPIENTS_LOCAL';
export const FETCH_RECIPIENTS_LOCAL_SUCCESS = 'FETCH_RECIPIENTS_LOCAL_SUCCESS';
export const FETCH_RECIPIENTS_LOCAL_FAIL = 'FETCH_RECIPIENTS_LOCAL_FAIL';

export const FETCH_RECIPIENTS_FOREIGN = 'FETCH_RECIPIENTS_FOREIGN';
export const FETCH_RECIPIENTS_FOREIGN_SUCCESS = 'FETCH_RECIPIENTS_FOREIGN_SUCCESS';
export const FETCH_RECIPIENTS_FOREIGN_FAIL = 'FETCH_RECIPIENTS_FOREIGN_FAIL';

export const SEND_TRANSFER_INFORMATION = 'SEND_TRANSFER_INFORMATION';
export const SEND_TRANSFER_INFORMATION_SUCCESS = 'SEND_TRANSFER_INFORMATION_SUCCESS';
export const SEND_TRANSFER_INFORMATION_FAIL = 'SEND_TRANSFER_INFORMATION_FAIL';

export const GET_OTP = 'GET_OTP';
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS';
export const GET_OTP_FAIL = 'GET_OTP_FAIL';

export const TOGGLE_MODAL_TRANSFER = 'TOGGLE_MODAL_TRANSFER';
export const TOGGLE_MODAL_ADD_RECIPIENT = 'TOGGLE_MODAL_ADD_RECIPIENT';

export const RESET_STORE = 'RESET_STORE';
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_VALUES_TRANFER = 'SET_VALUES_TRANFER';

export const TRACK_RECIPIENT_LOCAL = 'TRACK_RECIPIENT_LOCAL';
export const TRACK_RECIPIENT_LOCAL_SUCCESS = 'TRACK_RECIPIENT_LOCAL_SUCCESS';
export const TRACK_RECIPIENT_LOCAL_FAIL = 'TRACK_RECIPIENT_LOCAL_FAIL';

export const TRACK_RECIPIENT_FOREIGN = 'TRACK_RECIPIENT_FOREIGN';
export const TRACK_RECIPIENT_FOREIGN_SUCCESS = 'TRACK_RECIPIENT_FOREIGN_SUCCESS';
export const TRACK_RECIPIENT_FOREIGN_FAIL = 'TRACK_RECIPIENT_FAIL';
