export const FETCH_ALL_POI_TYPE = 'FETCH_ALL_POI_TYPE';
export const FETCH_ALL_POI_TYPE_SUCCESS = 'FETCH_ALL_POI_TYPE_SUCCESS';
export const FETCH_ALL_POI_TYPE_FAIL = 'FETCH_ALL_POI_TYPE_FAIL';

export const UPDATE_POI_TYPE = 'UPDATE_POI_TYPE';
export const UPDATE_POI_TYPE_SUCCESS = 'UPDATE_POI_TYPE_SUCCESS';
export const UPDATE_POI_TYPE_FAIL = 'UPDATE_POI_TYPE_FAIL';

export const ADD_POI_TYPE =  'ADD_POI_TYPE';
export const ADD_POI_TYPE_SUCCESS =  'ADD_POI_TYPE_SUCCESS';
export const ADD_POI_TYPE_FAIL =  'ADD_POI_TYPE_FAIL';

export const DELETE_POI_TYPE = 'DELETE_POI_TYPE';
export const DELETE_POI_TYPE_SUCCESS = 'DELETE_POI_TYPE_SUCCESS';
export const DELETE_POI_TYPE_FAIL = 'DELETE_POI_TYPE_FAIL';

export const RESET_STORE = 'RESET_STORE';