export const FETCH_TRANSACTION_HISTORY_LOCAL = 'FETCH_TRANSACTION_HISTORY_LOCAL';
export const FETCH_TRANSACTION_HISTORY_LOCAL_SUCCESS = 'FETCH_TRANSACTION_HISTORY_LOCAL_SUCCESS';
export const FETCH_TRANSACTION_HISTORY_LOCAL_FAIL = 'FETCH_TRANSACTION_HISTORY_LOCAL_FAIL';
export const RESET_STORE = 'RESET_STORE';