export const FETCH_TRANSACTION_HISTORY = 'FETCH_TRANSACTION_HISTORY';
export const FETCH_TRANSACTION_HISTORY_SUCCESS = 'FETCH_TRANSACTION_HISTORY_SUCCESS';
export const FETCH_TRANSACTION_HISTORY_FAIL = 'FETCH_TRANSACTION_HISTORY_FAIL';
export const RESET_STORE = 'RESET_STORE';