export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';
export const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_RESET_STATUS = 'CREATE_ACCOUNT_RESET_STATUS';

export const SEARCH_USERNAME = "SEARCH_USERNAME";
export const SEARCH_USERNAME_FAIL = "SEARCH_USERNAME_FAIL";
export const SEARCH_USERNAME_LOADING = "SEARCH_USERNAME_LOADING";
export const SEARCH_USERNAME_RESET = "SEARCH_USERNAME_RESET";

export const CREATE_PAYMENT_ACCOUNT = "CREATE_PAYMENT_ACCOUNT";
export const CREATE_PAYMENT_ACCOUNT_FAIL = "CREATE_PAYMENT_ACCOUNT_FAIL";
export const CREATE_PAYMENT_ACCOUNT_LOADING = "CREATE_PAYMENT_ACCOUNT_LOADING";
export const CREATE_PAYMENT_ACCOUNT_SUCCESS = "CREATE_PAYMENT_ACCOUNT_SUCCESS";


export const SEARCH_ACCOUNT_PAYMENT = "SEARCH_ACCOUNT_PAYMENT";
export const SEARCH_ACCOUNT_PAYMENT_SUCCESS = "SEARCH_ACCOUNT_PAYMEN_SUCCESS";
export const SEARCH_ACCOUNT_PAYMENT_FAIL = "SEARCH_ACCOUNT_PAYMENT_FAIL";
export const RESET_ACCOUNT_PAYMENT_STATUS = "RESET_ACCOUNT_PAYMENT_STATUS";

export const SEARCH_USERNAME_RECHARGE = "SEARCH_USERNAME_RECHARGE";
export const SEARCH_USERNAME_RECHARGE_RESET = "SEARCH_USERNAME_RECHARGE_RESET";

export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAIL= "UPDATE_BALANCE_FAIL";
export const UPDATE_BALANCE_RESET_STATUS = "UPDATE_BALANCE_RESET_STATUS";